### ISSUE TITLE
VM Completion Test never successful

### ISSUE THREAD

**Issue by acdino** [theJasonHelmick/PS-AutoLab-Env#100]
While running the config for devop-powershell-fundamentals, powershell has been stuck on VM Completion test for an hour and thirty seven minutes which roughly estimates to 35 failed tests and all of them immediately start over once the countdown ends and the test restarts. Is this normal or unusual? I know the information right below the test says it will take sometime at this part but the tests are immediately failed upon start. Any information is appreciated.

**Comment by acdino** [comment]
to add to that I just scrolled up and found a ton of red. Most of it stating that hyper-v was unable to find virtual machine with name 'cli1'. and then the other recurring error is "Virtual machine 'insert any of the VM's' could not be started because the hypervisor is not running. So now looking at that it would make sense that the test won't stop because it's not testing anything. How do I fix the above errors?

**Comment by Garypkay** [comment]
I'm having the same issue, did you get this resolved?

**Comment by theJasonHelmick** [comment]
Will be fixed in new release. Replacing Pester tests with CI cmdlets from Lability. This will remove the complexity of updating and writing Pester tests for every new configuration.

**Comment by Garypkay** [comment]
![download error](https://user-images.githubusercontent.com/29329310/27041057-c37339c2-4f8a-11e7-87a3-23fd040dcd90.JPG)
Thanks Jason, I don't get that fair now.
When Powershell is downloading the 2016_x64_EN_Eval.iso, it gets to 100% then an error is thrown - tried a few times today same error.

**Comment by Garypkay** [comment]
I forgot to add i have also tried 'Implement-Windows-Server-DHCP-2016' and 'Windows 10' in the configurations folder and similar error

**Comment by theJasonHelmick** [comment]
Thank you for the helpful information!  I'm investigating.

**Comment by acdino** [comment]
I won't close this issue because Garypkay is still resolving. But I believe I have solved my issue. Ended up being that the package actually installed all iso's and machines. Hyper visor was not running because in my BIOS settings virtualization was disabled when I thought it was enabled. Such a stupid mistake haha.

**Comment by theJasonHelmick** [comment]
Well, don't feel stupid.  I flex boot Win10 on my Mac -- Recently MS and Apple seem to be arguing about a possible security issue....the result is that Win10 got an update, followed by apple updating their EFI (think BIOS) which disables Win10 from recognizing that virtualization IS Enabled.  So, my development environment won't run any more.  In researching this issue, I saw several people running Win10 that had Hyper-v running, suddenly have to re-enable virtualization.  So I'm not really sure whats going on.  But - I am going to keep this Open so that I can test.  Thanks for the help!

**Comment by Garypkay** [comment]
Hi Jason
Please mark this as resolved. It must have been something on my laptop stopping it from running.
I purchased a SSD and re-installed Windows 10, then after following your instructions and it worked with out any issues.

Keep up the good work :-)

**Comment by theJasonHelmick** [comment]
Thank you!!!!   Good to hear!
