### ISSUE TITLE
VM Errors installing OS

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#12]
Received the following errors on VMs (see attached picture)
![hyper-verror](https://cloud.githubusercontent.com/assets/11599180/19236488/5202397a-8ebd-11e6-872a-e82fbaefd3d9.PNG)

OS won't build. Resetting VMs results in same result.

I believe the issue revolves around Secure Boot and perhaps is related to failing of hashes (Noted previously). If I have time, I'll attempt to disable secure boot in VM creation process to see if it resolves issue.

**Comment by theJasonHelmick** [comment]
ok .. great info - and I'll take a look today as well
Can you give me your OS version number?

**Comment by theJasonHelmick** [comment]
@themichaelbender @majst32 I found the issue... it with Win 10 Anniversary edition -- can you confirm your edition version?  Here is the article - I will see if I can come up with a way around this for now.
https://social.technet.microsoft.com/Forums/windowsserver/en-US/8c0d9f19-873e-416d-9124-568ca43bf924/hyperv-configuration-version-80-windows-boot-manager-error-0xc0000603-in-windows-10-build143935?forum=WinServerPreview

**Comment by theJasonHelmick** [comment]
@themichaelbender @majst32 Here is a temporary workaround you might try -- but I'm trying to see if I can something better ---
https://support.microsoft.com/en-us/kb/3172729

**Comment by theJasonHelmick** [comment]
@themichaelbender @majst32 I have merged the solution into master and will issue a new release tonight v2.1.0.  I'm going to close this issue for now.
