### ISSUE TITLE
Create and prioritize "Allow Any/Any" firewall rule on all machines

### ISSUE THREAD

**Issue by greggoindenver** [theJasonHelmick/PS-AutoLab-Env#14]
If I'm reading these correctly, we're setting the firewall on these machines to a rather restricted setting -- allowing ping and file sharing.  

Can we adjust the default firewall setting for all machines to "Allow Any/Any" in both directions?  This isn't shutting down the firewall, which has implications all its own, but it does set it to wide open.

Although, yes, it isn't the right practice in production, this config in the lab greatly eases the job of teaching this content.  If I'm trying to teach someone how to merely _connect_ to Active Directory, having to also include a firewall conversation begins severely complicating that message.

Doing so lets each author, on a case-by-case basis, determine whether/when to apply more restrictive firewall rules in our individual courses as appropriate.

**Comment by theJasonHelmick** [comment]
I'll explain on the call. But yes.  You can modify your configs for whatever you want.  Mine are just examples. 

_________________________________

Jason Helmick
Author/Evangelist | Pluralsight
www.pluralsight.com

**Comment by theJasonHelmick** [comment]
I'm going to close this as it is currently author definable.
