### ISSUE TITLE
PS-AutoLab-Env v3.0.2 - Missing Course? 

### ISSUE THREAD

**Issue by YTJeff** [theJasonHelmick/PS-AutoLab-Env#140]
Hi 

Iv just downloaded and extracted the PS-AutoLab-Env v3.0.2 file, but upon following the instructions in the "Putting Powershell to work" course from Pluralsight it advises to navigate to C:\AutoLab\Configurations\Windows10
My issue is i don't see the Windows 10 configuration, i see devops-powershell-fundamentals, Implement-Windows-Server-DHCP-2016, Jason-DSC-Env, microsoft-powershell-implementing-jea. 

Am i doing something wrong here? 

Thanks

**Comment by jdhitsolutions** [comment]
Go to https://github.com/jdhitsolutions/Windows10 to download it. Follow the instructions in the README.

**Comment by YTJeff** [comment]
Thank you very much
