### ISSUE TITLE
Password issues?

### ISSUE THREAD

**Issue by qw3rt33** [theJasonHelmick/PS-AutoLab-Env#146]
My PS_AutoLab setup seems to have gone smoothly, but when I try to log into the Win10  VM, it doesn't seem to be accepting the default password set? Anyone know if the password is different or a way to bypass the security altogether?

**Comment by qw3rt33** [comment]
I think I wrote this issue prematurely...turns out AutoLab has a US configuration and I'm in the UK...different keyboard layout!

**Comment by bolivaralejandro** [comment]
The second character for the password is not &, it is @.
