### ISSUE TITLE
Eliminate the joke users (Don/Jason/Greg/Simon) prior to using these in production

### ISSUE THREAD

**Issue by greggoindenver** [theJasonHelmick/PS-AutoLab-Env#15]
They're cute, but we are creating something professional here for potentially widespread usage.

**Comment by theJasonHelmick** [comment]
Damn. I will today. Ment to pull those.   Will have an updated release tonight.  Thanks for catching that. 

_________________________________

Jason Helmick
Author/Evangelist | Pluralsight
www.pluralsight.com

**Comment by majst32** [comment]
I can pull them from the configs on the dev branch...

**Comment by theJasonHelmick** [comment]
Missy — I already fixed

_________________________________

Jason Helmick
Author/Evangelist | Pluralsight
www.pluralsight.com <http://www.pluralsight.com/>

**Comment by theJasonHelmick** [comment]
@greggoindenver @majst32 this has been merged into master and will become part of the new release v2.1.0 tonight.  Closing this issue -- Thanks for catching the Greggo!
