### ISSUE TITLE
Document and/or build script for use of "Standalone" scripts.

### ISSUE THREAD

**Issue by greggoindenver** [theJasonHelmick/PS-AutoLab-Env#18]
We need some dead-easy-to-understand documentation for how to use the "Standalone" scripts, those that'll be used by Authors who won't be using the Lability "AutoLab" approach.

**Comment by theJasonHelmick** [comment]
Agreed. I will see if I can build the basics of DSC down for those.

**Comment by theJasonHelmick** [comment]
Completed
