### ISSUE TITLE
Document use of Lability script with VMware Workstation

### ISSUE THREAD

**Issue by greggoindenver** [theJasonHelmick/PS-AutoLab-Env#19]
Specifically setting the OS configuration to "Hyper-V (unsupported)" and not "Windows 10 x64).

**Comment by theJasonHelmick** [comment]
Thank you Greg!  I'm adding to documentation now

**Comment by theJasonHelmick** [comment]
I'm going to leave this open for a while just in case no one reads the documentation ;)

**Comment by theJasonHelmick** [comment]
Updated -- closing issue
