### ISSUE TITLE
Because setup-lab.ps1 actually modifies a host machine, it may need a legal statement.

### ISSUE THREAD

**Issue by greggoindenver** [theJasonHelmick/PS-AutoLab-Env#24]
The other scripts don't make fundamental changes on a machine, but your setup-lab.ps1 script actually makes modifications onto the host machine.  Since that host machine could (and likely would) be the user's primary machine, we should ask Pluralsight legal about whether we should add a legal statement.

**Comment by majst32** [comment]
Do you think this would be a Pluralsight-specific legal statement or just a generalized one??

**Comment by greggoindenver** [comment]
If we need it, it would be "one that's blessed by Pluralsight legal".

**Comment by majst32** [comment]
@thejasonhelmick, I will defer to you on this.  Just thinking it would be odd if people outside PS like me use this.

**Comment by theJasonHelmick** [comment]
hmmm.... interesting -- was thinking a lot would use it for easy lab setups......but yea....I'll check with our internal legal

**Comment by themichaelbender** [comment]
Actually, I was telling one of my colleges at the college about it, and he thought it was a great idea. If I had this tool over the years, it would have saved me hundreds of hours building VMs. I'll be using in for sure with future classes.

**Comment by jdhitsolutions** [comment]
Nobody is making use of this project a mandatory requirement.  I don't see why this is even an issue.

**Comment by theJasonHelmick** [comment]
Added the following on my own:
This tool is provided 'as is' with no warrenties or guarantees.
