### ISSUE TITLE
RFC - Graphical front-end for AutoLab

### ISSUE THREAD

**Issue by timothywarner** [theJasonHelmick/PS-AutoLab-Env#25]
Entry-level students who haven't reached their learning curve with PowerShell may get mired in the AutoLab details. Same for _some_instructors.

Suggest creating a simple, single-form GUI layer on top of AutoLab.

**Comment by theJasonHelmick** [comment]
Can everyone please leave their comments regarding this?

**Comment by jdhitsolutions** [comment]
Yes, I think @timothywarner should do this.

**Comment by theJasonHelmick** [comment]
@timothywarner --- after the 3.0.o release....this week, it would be a good time to make your GUI frontend! ;)

**Comment by timothywarner** [comment]
OK. I'll give it a whirl.

**Comment by theJasonHelmick** [comment]
Status?  Should we close this for now, or discuss?  I'm currently considering a control script Menu interface rather than a Winform  @timothywarner @jdhitsolutions

**Comment by timothywarner** [comment]
You may close. A command-line menu makes more sense. Thanks.

_________________________

*Tim Warner*
Nashville, TN
timothywarner316@gmail.com
615-480-4939
Twitter <https://twitter.com/techtrainertim> | Website
<http://timwarnertech.com>
