### ISSUE TITLE
Split-brain scenario with PS-Auto-Lab and Lability folders

### ISSUE THREAD

**Issue by benpiper** [theJasonHelmick/PS-AutoLab-Env#26]
Line 66 of [setup-host.ps1](https://github.com/theJasonHelmick/PS-AutoLab-Env/blob/master/Setup-Host.ps1#L66) forcibly copies the Configurations folder from C:\PS-AutoLab-Env\Configurations\ to C:\Lability\Configurations. The Lability scripts use the latter, and that works fine. But there are some potential problems:
- If someone wants to modify the configurations or create new ones and push those to a repo, they have to manually copy those configs back to the folder in PS-AutoLab-Env.
- If someone has already made changes to the configurations in the Lability folder and inadvertently runs setup-host.ps1 again, it will overwrite their configs.

Two possible fixes come to mind:
- Symbolically link ?:\Lability\Configurations to ?:\PS-AutoLab-Env\Configurations.
- Alternately, remove the ?:\Lability\Configurations folder and just point the scripts to ?:\PS-AutoLab-Env\Configurations

**Comment by Freeflypete** [comment]
I had a related issue. When I downloaded the files from Github I placed them on my V: drive in a folder called "PS-AutoLab-Env-2.1.0" which is what you get when you extract it. This caused the copy to fail at line 66 as it looks for C:\PS-AutoLab-Env\Configurations\ . 

I suggest the relative path is used on Line 66 for the source copy location to make it more resilient

**Comment by theJasonHelmick** [comment]
See issue #27 -- I agree and will fix, however this is a breaking change and I'm trying to collect and make those all at once --- I will put into Master sometime this week for testing as Unreleased @majst32 @Freeflypete @benpiper

**Comment by theJasonHelmick** [comment]
Still a work in progress -- should have resolve in next release 2.2 later this week

**Comment by theJasonHelmick** [comment]
Master has been updated with pull request from @g0t4 -- has not been tested -- would love some help with that @benpiper  @Freeflypete @majst32

**Comment by theJasonHelmick** [comment]
I updated and fixed a bug --- this will be in master tonight -- and in the next release

**Comment by g0t4** [comment]
Thanks Jason.
