### ISSUE TITLE
Error Setting up windows11/windows10 Autolab/Inability to automatically create NetNat

### ISSUE THREAD

**Issue by victorlanso** [theJasonHelmick/PS-AutoLab-Env#267]
![Autolab](https://github.com/user-attachments/assets/1b69f9eb-bd86-4a73-99b3-d1c464d67d66)

**Comment by jdhitsolutions** [comment]
I have built the Windows 11 lab many times on different machines with no errors, so let's see what is different about your setup. First, run `Get-PSAutoLabSetting` and post the result.  I am assuming no VM gets created.

**Comment by victorlanso** [comment]
![image](https://github.com/user-attachments/assets/c9b9f670-da16-4214-989d-ed68752f71d8)

Initially, I have deployed the Autolab and everything was working fine. But while trying to upgrade to the latest version, I can only setup servers but windows11/windwos10 are showing errors.

**Comment by jdhitsolutions** [comment]
Are you logged on with an account name of 'Administrator'? If so, that is the problem.  The configuration assumes you are logged on to your desktop with an account **other** than Administrator, such as `victor`. The configuration will create a local admin account in the VM called `victor` using the lab's default password. It also sets the local administrator account in the VM to the same password. 

Either log on with a different account, or edit the `VMConfiguration.ps1` file and comment out this section:

```powershell
        #create a local account with the same name as the person
        #running this config
        user $env:username {
            UserName               = $env:username
            Disabled               = $false
            Password               = $credential
            PasswordChangeRequired = $false
            PasswordNeverExpires   = $True
        }
```

This should get you past the duplicate resource problem. Then you can log on to the VM using the VM's local administrator account.

**Comment by victorlanso** [comment]
I comment out the 

> Are you logged on with an account name of 'Administrator'? If so, that is the problem. The configuration assumes you are logged on to your desktop with an account **other** than Administrator, such as `victor`. The configuration will create a local admin account in the VM called `victor` using the lab's default password. It also sets the local administrator account in the VM to the same password.
> 
> Either log on with a different account, or edit the `VMConfiguration.ps1` file and comment out this section:
> 
> ```powershell
>         #create a local account with the same name as the person
>         #running this config
>         user $env:username {
>             UserName               = $env:username
>             Disabled               = $false
>             Password               = $credential
>             PasswordChangeRequired = $false
>             PasswordNeverExpires   = $True
>         }
> ```
> 
> This should get you past the duplicate resource problem. Then you can log on to the VM using the VM's local administrator account.

I commented out the section as instructed and the lab setup was successful. Thank you so much for your support and mentorship.

**Comment by jdhitsolutions** [comment]
Glad you got it working. I will have to double-check the documentation to make sure I mention this.
