### ISSUE TITLE
The C:\Lability location is hardcoded

### ISSUE THREAD

**Issue by benpiper** [theJasonHelmick/PS-AutoLab-Env#27]
Instead of hard coding the location of Lability files, allow the user to specify the location by modifying a variable in setup-host.ps1. C:\Lability probably works fine for 90%+ of people, but there may be that outlier who doesn't have the space to store all those ISOs on their C: drive.

**Comment by jdhitsolutions** [comment]
I totally agree with this. I try to avoid installing anything on C:. This is most likely an issue for the Lability project.

**Comment by benpiper** [comment]
There's a HostDefaults.json file that controls the defaults. I copied this file into my fork and adjusted the Setup-Host.ps1 script to copy it into the PoSH module directory just as it does with the media.json file.

**Comment by theJasonHelmick** [comment]
@benpiper @jdhitsolutions @majst32  Not only can an author choose to modify the HostDefaults.json, there are two cmdlets that allow this modification --- however this needs to be done in the setup-host before the lab configuration is built.  So I'm going to let this be Author definable --- EXCEPT---

If you want, I can change the folder for the entire project to something other than Lability, like "Pluralsight" - but I do want to leave it off of C; so its easy for students to A) find and delete, B) not have even longer paths to type to run a config.

So, if you would like me to change the folder name for the entire project, please let me know what you think would be best. -- And thank you for the comments!!!!

**Comment by benpiper** [comment]
Changing the folder name to "Pluralsight" and leaving the default as C: sounds ideal. It will also be easier for learners to remember the location.

**Comment by theJasonHelmick** [comment]
@benpiper @jdhitsolutions @majst32 I agree and also with some other comments that I have received to not hard code the system drive (C:) -- Changing the folder name and not harding the C: drive is a breaking change, so this will affect the major release number -- I will fix this week and push to master as unreleased -- but I want to try and catch as many breaking changes as I can first.  Cheers

**Comment by theJasonHelmick** [comment]
This was fix by pull request
