### ISSUE TITLE
GroupScope='Universal' should be GroupScope='Global' in DSC scripts (all).

### ISSUE THREAD

**Issue by greggoindenver** [theJasonHelmick/PS-AutoLab-Env#28]
Universal groups are generally used only for Exchange and the rare, occasional cross-domain membership.

**Comment by jdhitsolutions** [comment]
Is there anything you see that would break using universal groups? Or put another way is there any benefit to this project using global groups?

**Comment by greggoindenver** [comment]
Reason:  Proper form.  They're not typically used in actual environments except in special multi-domain situations and for Exchange distribution groups.  Moreover, it'll make things uncomfortable for whomever's doing the "Instal and Configure ADDS" course for 70-742, where they'll need to explain when/where to use each group type.

**Comment by theJasonHelmick** [comment]
I will update the new Master config that I'm building with @majst32 to include Global groups. @greggoindenver

**Comment by theJasonHelmick** [comment]
Completed in the new Master config -- not released yet - will in 2.2 -- available now from master
