### ISSUE TITLE
Exclude version # in folder in zip file for releases

### ISSUE THREAD

**Issue by g0t4** [theJasonHelmick/PS-AutoLab-Env#30]
Could we exclude the version # from the folder inside the zip file for a release? How about only put it in the zip file name?

I copied the embedded folder as is onto my C drive (C:\PS-AutoLab-Env-2.1.0) and the setup failed at the end because it couldn't find files to copy. Another idea, the setup could run a sanity check before it runs to ensure that files are in the correct place.

Also, is there a way we could get rid of this dual folder thing? Why is it necessary to have C:\PS-AutoLab-Env and C:\Lability?  - nevermind - I see that this is just for installation purposes now

**Comment by g0t4** [comment]
I created a pull request to address this by using $PSScriptRoot

**Comment by g0t4** [comment]
My pleasure, did you see the pull request for this? I tested locally and
seems ok from a different folder.

**Comment by g0t4** [comment]
Also what about just running the configurations from the checkout
directory? Is c:\Lability a requirement of Lability? If so maybe we can
apply the same change to Lability so that can be in any location and then
we could just git clone and run right where we checkout.

That would also be nice for defining new configs, and changing configs, to
not need to copy files back to a repo folder to check them in.

**Comment by theJasonHelmick** [comment]
In progress --- will try on next release (3.0.0)

**Comment by theJasonHelmick** [comment]
So -- the version is something the Github assigns.....I haven't been able to remove ---- if someone wants to try and research -- willing to accept advice. @jdhitsolutions @g0t4 @majst32

**Comment by g0t4** [comment]
This issue is no longer a problem after #32
