### ISSUE TITLE
Configuring Trusted Hosts 

### ISSUE THREAD

**Issue by jdhitsolutions** [theJasonHelmick/PS-AutoLab-Env#4]
I think configuring Trusted Hosts should be a bit more forgiving and selective. The way I see the existing code you are forcing the user to set set Trusted Hosts to *. Or if they already have a setting you can't make any changes. It seems the only thing that needs to be added is the new subnet. We should be able to get that from a global setting or at least prompt the user to enter a value, or even skip it altogether.

**Comment by theJasonHelmick** [comment]
How about if I (or you) change it to add * to the array and not worry about other its and such?

**Comment by jdhitsolutions** [comment]
I think I've tried that in the past. If you already have settings, you can't concatenate *.  I think you can only have the wildcard or specific settings.

**Comment by jdhitsolutions** [comment]
Now that I think about TrustedHosts only needs to be configured to allow access to the lab subnet and/or a list of computers like 'DC,S*'. That could be concatenated unless the user is already set to *.

**Comment by theJasonHelmick** [comment]
The only challenge to this is that each Author, and perhaps student, will need to modify this list.  I know that different authors will use different computer names and IP address that are set in the PSD1 -- jsut don't know if I want to have another config file that needs to be modified.

**Comment by majst32** [comment]
Can we read it in from the PSD1?

**Comment by theJasonHelmick** [comment]
@majst32 I think we should do this, but automation timing is an issue. I'm currently doing this during the initial host setup in Setup-Host -- We would have to do this in a per configuration Setup-Lab script - Maybe @jdhitsolutions  can help us with a simple modification to read the psd1.

**Comment by benpiper** [comment]
Would using PowerShell Direct instead avoid having to touch the Trustedhosts setting?

**Comment by jdhitsolutions** [comment]
PowerShell Direct won't work for older operating systems that someone might need to set up.

**Comment by theJasonHelmick** [comment]
ok @jdhitsolutions @majst32 @benpiper @g0t4 -- I am now in a position to read this automatically from the configuration data -- a list of IP addresses -- and add them to trusted hosts.  I can also clean them out when the lab is wiped --- is this something we want to add or is using * fine for a lab environement. --- remember, this is just a lab -- not production.  Comments?

**Comment by g0t4** [comment]
I would vote KISS and assume this is only for a lab env.

**Comment by theJasonHelmick** [comment]
I vote KISS too!  Thanks Wes -- Anyone else want to respond?  I really don't mind adding the ability -- just not sure its really needed for something that will always be for a lab environement - Thanks to @jdhitsolutions , its only adding * to the existing array and not wiping out any original settings.

**Comment by benpiper** [comment]
I agree that it's okay for a lab environment. The only thing that may be worth adding is a switch that asks the user if they want to set TrustedHosts to * or just handle it themselves.

**Comment by theJasonHelmick** [comment]
As discussed in #76 -- I agree -- closing this to have discussion there
