### ISSUE TITLE
Hard code admin passwords

### ISSUE THREAD

**Issue by jdhitsolutions** [theJasonHelmick/PS-AutoLab-Env#44]
The goal of this project is to streamline setup of a test environment. As such there's no need to prompt for administrator passwords to be used. We can simply set a default of P@ssw0rd. If someone wants to change it, they can after after the lab is complete. 

Not prompting for a password removes the possibility of error in entering in a password or forgetting what you entered. It also makes it easier for us to have a completely unattended install.

**Comment by theJasonHelmick** [comment]
Agreed -- will Dev and test. Will try to get in 3.0.0 (the next ) release

**Comment by theJasonHelmick** [comment]
Done -- P@ssw0rd ...
