### ISSUE TITLE
AutoLab presentation for Viewers

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#5]
Will there be an intro course for this series that runs through the Autolab, or are we expected to set it up for viewer during first/last module?

**Comment by theJasonHelmick** [comment]
I will be making a video setup guide for students in a couple of weeks after we finish adding a couple more configs 

_________________________________

Jason Helmick
Author/Evangelist | Pluralsight
www.pluralsight.com
