### ISSUE TITLE
Issue running script until network switched to private

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#6]
You may wish to add a check of the network profile on the local machine to ensure it is either domain or private. I ran an issue because it was Public, thus winrm won't start properly and no trusted hosts. Setting to private fixed via Set-NetConnectionProfile -InterfaceIndex 8 -NetworkCategory Private.

**Comment by theJasonHelmick** [comment]
Accepted and thank you!

**Comment by themichaelbender** [comment]
Would you like me to work on this?

**Comment by theJasonHelmick** [comment]
@themichaelbender @majst32 Bro - it would be awesome if you wanted to us out on this.  I'm figuring the solution will have to be in the first script at the root -- Setup-Host.ps1  So if you got a way to do it - let's give it a shot!  Thanks man!

**Comment by themichaelbender** [comment]
Finished!

**Comment by majst32** [comment]
I will send you instructions for github today.  @thejasonhelmick - what branch do you want this on?

**Comment by theJasonHelmick** [comment]
Fork and send Pull request to Master — I can then try in my Dev — I’m doing another release for a week or so……so I can add this to the unreleased stuff .

_________________________________

Jason Helmick
Author/Evangelist | Pluralsight
www.pluralsight.com <http://www.pluralsight.com/>

**Comment by benpiper** [comment]
Would adding the ` -SkipNetworkProfileCheck` argument be sufficient?

**Comment by themichaelbender** [comment]
Probably...

**Comment by themichaelbender** [comment]
I tested and this appears to work so @thejasonhelmick can ignore my code changes.

**Comment by g0t4** [comment]
I would prefer to avoid changing the host's network profile. The error message right now is pretty helpful but maybe Lability could wrap this with a more helpful error or apply the above flag to work with public profiles?

**Comment by themichaelbender** [comment]
Using @benpiper's suggestion of -SkipNetworkProfileCheck appears to fix this issue. I do not have the resources at this time to verify this in code for all platforms. Also, the step @g0t4 is referring to is part of the setup-hosts.ps1, not Labability components. See line 30.

**Comment by g0t4** [comment]
We need a CI server :) - would that be legal?

**Comment by majst32** [comment]
+1, @g0t4.  I said the same thing!!

**Comment by theJasonHelmick** [comment]
Fixed and will be in next release
