### ISSUE TITLE
Unnattend-lab error running script

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#60]
Every time I run Unattend-lab, I receive the following error:
Write-NodeMOFFile : Invalid MOF definition for node 'DC1': Exception calling "ValidateInstanceText" with "1" argument(s):
"Undefined property PrefixLength
 At line:19, char:2
 Buffer:
onName = "AutoLab";
};^
insta
"
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 char:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

@greg-shields mentioned to me that their was a change in the DSC resource, XIPAddress, and that I needed to change references to subnetmask to PrefixLength. I'm not sure where to do this, if in fact it is a fix.

Please advise as I'm currently unable to proceed with my course development.

Thanks.

**Comment by majst32** [comment]
xIPAddress is in the xNetworking module.  We're currently using 3.0.0.0 as of this release... apparently 3.0.0.0 doesn't play nicely with older versions... suggest removing any older versions of xNetworking and trying again as a workaround for now?

**Comment by MikeShepard** [comment]
That worked for me, at least with the test-singleserver configuration.

**Comment by theJasonHelmick** [comment]
WE already have changed subnetmask to prefixlength because of the change in xIPAddress. So @themichaelbender , you dont have to change anything.  Just make sure to remove old versions of the xNetworking module.  Will automate this in the future -- Jeff hicks has code for this. @jdhitsolutions

**Comment by themichaelbender** [comment]
Deleting the old module folders resolved this issue.

Thanks!
