### ISSUE TITLE
Checksum fail

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#7]
With the current script using TP5, the checksums are failing during setup-lab.ps1. It appears they don't match. I've run through this twice with the same outcome.

VERBOSE: [7:54:27 PM] Calculating resource 'C:\Lability\ISOs\2016TP5_x64_EN.iso.checksum' checksum.
VERBOSE: [7:54:40 PM] Writing checksum '4D46EC27EA02B3255B2D6738241F71DB' to resource 'C:\Lability\ISOs\2016TP5_x64_EN.iso.checksum'.
VERBOSE: [7:54:40 PM] Resource 'C:\Lability\ISOs\2016TP5_x64_EN.iso' checksum does not match '6417BA460F95BD91DED05DFACD553783'.
Web resource 'http://care.dlservice.microsoft.com/dl/download/8/9/2/89284B3B-BA51-49C8-90F8-59C0A58D0E70/14300.1000.160324-1723.RS1_RELEASE_SVC_S
ERVER_OEMRET_X64FRE_EN-US.ISO' download failed.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.0\Lib\Resource.ps1:256 char:13
+             throw ($localized.WebResourceDownloadFailedError -f $Uri) ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Web resource 'h...ownload failed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Web resource 'http://care.dlservice.microsoft.com/dl/download/8/9/2/89284B3B-BA51-49C8-90F8-59C0A58D0E70/14300.100 
   0.160324-1723.RS1_RELEASE_SVC_SERVER_OEMRET_X64FRE_EN-US.ISO' download failed.

**Comment by theJasonHelmick** [comment]
Checking into this --

**Comment by jdhitsolutions** [comment]
Is it possible the source ISOs have changed and the checksums are now wrong? Does the ISO download and can you use it? If so, then the checksum is merely an "accounting" problem.

**Comment by themichaelbender** [comment]
If there was an optional to accept different hashes and move on, that would be great.

The ISO downloads and is useable.

**Comment by theJasonHelmick** [comment]
Michael, I think I have discovered this issue, but it would help if you could confirm a few things.  First, is the message your seeing after the download in Yellow or Red?
<img width="1230" alt="screen shot 2016-10-09 at 5 26 07 pm" src="https://cloud.githubusercontent.com/assets/12662278/19224972/a53cf170-8e45-11e6-99a4-6d6261517842.png">
If yellow as in the image, thats not an error -- it is a test that failed that prompted the download.

I believe what is happening is that after the download the script hangs -- but if you hit the return key it will continue.  I will track this with the lability guys.

**Comment by themichaelbender** [comment]
Appears to work now. Previous runs had no 'Press Enter' and script broke. Gremlins.

**Comment by theJasonHelmick** [comment]
There is no 'Press Enter' -- its a bug in either PowerShell or Lability -- so I'm checking with the lability guys. I've had this happen with regular PowerShell scripts and long running processes -- so I'm half thinking its PowerShell and there is nothing I can do about that -- except warn students in the ReadMe.md and message that displays before the download begins.  I've already changed those to reflect this possibility -- but I will report back here when I find out more. Thanks for the help!

**Comment by themichaelbender** [comment]
The only thing I received this pass was another 'Press R to run once' prompt. Seemed to work this time. Will check later today. Thanks.
