### ISSUE TITLE
Adding additional VMs to Lab

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#73]
Is it possible to add additional VMs into an existing lab environment without impacting the current states of the existing VMs? After building and configuring my custom course environment, I now need another client VM.

**Comment by jdhitsolutions** [comment]
I don't see anything preventing you from creating additional VMs after the fact. They just wouldn't be part of any snapshots or rollback efforts.

**Comment by superdale007** [comment]
Can't I just add a new nodename section in the VMConfigurationData.psd1 file?

**Comment by jdhitsolutions** [comment]
You can modify the psd1 file to add more VMs. These would then be part of any command that manages the entire lab configuration. I believe the question was about manually adding another server to the environment after the lab has been created. There's no reason you can do this manually, but Lability and tools in this project would ignore it.

**Comment by themichaelbender** [comment]
Actually Dale's response was what I was looking to do. I've talked with Jason and will be testing how this works at a later time. In theory, adding it and re-running setup-lab should build it out and not impact existing lab. I'll let you know in a couple of weeks.

**Comment by superdale007** [comment]
Let me know!

**Comment by themichaelbender** [comment]
Will do, Bruce!

**Comment by superdale007** [comment]
Dude....If you can't keep a secret, i'll revoke your "BatCave-Pass"! ;-)
