### ISSUE TITLE
LabNAT not working

### ISSUE THREAD

**Issue by superdale007** [theJasonHelmick/PS-AutoLab-Env#75]
So everything seems to running fine, but when I type Enable-Internet, i don't get an error, but I don't see a switch in Hyper-V appear for it...only my physical and LabNET (not NAT).

**Comment by jdhitsolutions** [comment]
This isn't creating a new switch. If you run Get-VMSwitch you should see one called LabNet which is internal. Run Get-NetNat. That is what Enable-Internet is creating.

**Comment by superdale007** [comment]
OOOOKkkkkk.....so if "Enable-Internet" doesn't create a switch...what does it do? After you do a setup-lab you get "To enable Internet access for the VM's, run: Enable-Internet".... I assumed that meant it would setup a NATed enviroment...but nothing happened...I got a returned command prompt within 1/2 second.... UPDATE: I redid my installation tonight...this time when I ran Enable-Internet, I did get come output:

IPAddress         : 192.168.3.1
InterfaceIndex    : 35
InterfaceAlias    : vEthernet (LabNet)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Tentative
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 192.168.3.1
InterfaceIndex    : 35
InterfaceAlias    : vEthernet (LabNet)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Invalid
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : PersistentStore


If I type Get-NetNat....nothing...just a command prompt (within 1/2 second)

**Comment by jdhitsolutions** [comment]
You should look at the module file and see what the Enable-Lab function is doing. I know that the NAT cmdlets are still a little jiggly in the middle. Still, something seems off here. What operating system are you running and what version of PowerShell (use $PSVersionTable).

**Comment by theJasonHelmick** [comment]
So, the Switch name is specified in the Configuration Data -- it gets created when the lab env is built. The Enable-Internet then turns on the nat based on that name.  Are we good to close this?

**Comment by superdale007** [comment]
Yep

Please excuse any typos as this email is coming from my non-fruity phone ;-)

W. Dale Meredith
MCT, MCSE, MCTS, MCSA, MCITP, CEH, CEI, Pluralsight Author
My Mentored Learning, Inc.
email: dale.meredith@hotmail.com
________________________________

**Comment by theJasonHelmick** [comment]
Thank you Dale!
