### ISSUE TITLE
Use standard names in PSAutolab module

### ISSUE THREAD

**Issue by jdhitsolutions** [theJasonHelmick/PS-AutoLab-Env#80]
I realize you intentionally wanted to use non-standard names for commands like Run-Lab and Setup-Lab. However, now that these are part of a module, PowerShell will complain about non-standard verbs if you import the module. I think the better approach would be to rename the commands using standard verbs. Then create aliases using the current names like Run-Lab.  This should satisfy module requirements and not break anything.

**Comment by theJasonHelmick** [comment]
AS mention in issue 92, I will address.

**Comment by jdhitsolutions** [comment]
No reason to keep this open then.
