### ISSUE TITLE
Errors running unattend-lab

### ISSUE THREAD

**Issue by BillJarrett** [theJasonHelmick/PS-AutoLab-Env#93]
I'm getting the following errors when I run unattend-lab on two different Windows 10 machines:

At C:\AutoLab\Configurations\TEST-SingleServer\VMConfiguration.ps1:26 char:5
+     Import-DSCresource -ModuleName PSDesiredStateConfiguration,
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not find the module '<xActiveDirectory, 2.14.0.0>'.
At C:\AutoLab\Configurations\TEST-SingleServer\VMConfiguration.ps1:385 char:9
+         xAdcsCertificationAuthority ADCSConfig
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
Undefined DSC resource 'xAdcsCertificationAuthority'. Use Import-DSCResource to import the resource.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ModuleNotFoundDuringParse
 
Building the lab environment
Cannot locate node 'C:\AutoLab\Configurations\TEST-SingleServer\S1.mof' file. No DSC configuration will be applied.
Ensure the DSC configuration has been run successfully.
At C:\Program Files\WindowsPowerShell\Modules\Lability\0.10.1\Src\LabConfiguration.ps1:85 char:17
+ ...              throw ($localized.CannotLocateMofFileError -f $mofPath);
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot locate n...n successfully.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot locate node 'C:\AutoLab\Configurations\TEST-SingleServer\S1.mof' file. No DSC con
   figuration will be applied. Ensure the DSC configuration has been run successfully.

**Comment by BillJarrett** [comment]
I saw a similar issue which was resolved by upgrading the machine to 1607, but I'm already at 1607 and my $PSVersionTable looks like:

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by BillJarrett** [comment]
Ok, I think I solved this. First, I had to run the following commands:

Install-Module -Name xActiveDirectory - Change to 2.16.0.0
Install-Module -Name xDhcpServer
Install-Module -Name xPendingReboot
Install-Module -Name xADCSDeployment - Change to 1.1.0.0

Then, I needed to edit the file C:\AutoLab\Configurations\TEST-SingleServer\VMConfiguration.ps1 in the area of line 25-34. I changed the ModuleVersion on xActiveDirectory to 2.16.0.0 and the ModuleVersion on xADCSDeployment to 1.1.0.0

**Comment by jdhitsolutions** [comment]
The setup process should have downloaded the modules for you. But this is an older test configuration so I suppose anything could go wrong.

**Comment by theJasonHelmick** [comment]
Will test for issue in new version that is under development. Closing this issue for now
