### ISSUE TITLE
Error with checksum

### ISSUE THREAD

**Issue by themichaelbender** [theJasonHelmick/PS-AutoLab-Env#98]
Any know where this issue is coming from?

I downloaded the current version and I'm running on a clean machine. I did not have this issue when new version came out. Concerned as this version and the configuration are tied to my Pluralsight course.

Error:
Building the lab environment
GetResourceDownload : A parameter cannot be found that matches parameter name 'ThrowOnError'.
At line:114 char:41
+         $resource = GetResourceDownload @PSBoundParameters;
+                                         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [GetResourceDownload], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,GetResourceDownload
 
Resource download 'C:\AutoLab\ISOs\2016_x64_EN_Eval.iso' checksum does not match '18A4F00A675B0338F3C7C93C4F131BEB'.
At line:135 char:13
+             throw ($localized.ResourceChecksumMismatchError -f $Desti ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Resource downlo...7C93C4F131BEB'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Resource download 'C:\AutoLab\ISOs\2016_x64_EN_Eval.iso' checksum does not match '18A4F00A675B0338F3C7 
   C93C4F131BEB'.

Thanks.

Mike

**Comment by acmatemu** [comment]
Hi,

Experiencing this error on current build, how was this solved for you?
