### ISSUE TITLE
When setting up what is the most basic config?

### ISSUE THREAD

**Issue by acdino** [theJasonHelmick/PS-AutoLab-Env#99]
My pluralsight course teacher unfortunately did not leave a config setup to choose for our AutoLab. So I wanted to know what is the most basic config to use? Thanks for the help.

**Comment by jdhitsolutions** [comment]
That is hard to say without knowing the course or topic.

**Comment by acdino** [comment]
I apologize, the group of courses is titled Configuring Windows Devices (70-697). The first course in the group is by Glenn Weadock called Lab Setup. In the second module of this course called First Steps, he mentions using the PluralSight Auto Lab for "snagging the eval of server 2016" and "snagging the eval of windows 10". Any help is much appreciated.

**Comment by jdhitsolutions** [comment]
In that case, if I were watching the course I'd probably use the Devops PowerShell Fundamentals. It might install a bit more than you'll need. But better to have options I suppose.  And it will create a domain which you might need.

**Comment by acdino** [comment]
That's what I was thinking to when I was reading through the lab definition for that config, but didn't want to spend hours downloading if it was unnecessary. Thank you so much, I really appreciate the help.
